<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurriculumSubjectsSeeder extends Seeder
{
    private const TUITION_PER_UNIT = 364.00;
    private const LAB_FEE_PER_SUBJ = 1656.00;

    public function run(): void
    {
        $subjects = [

            // ================================================================
            // BS COMPUTER SCIENCE — 1st Year, 1st Semester
            // Billable: 22 lec units, 4 lab subjects → ₱19,332 total
            // ================================================================
            [
                'code'           => 'BSCS-GE1-1-1',
                'name'           => 'Purposive Communication',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-GE2-1-1',
                'name'           => 'Mathematics in the Modern World',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-GE3-1-1',
                'name'           => 'Science, Technology and Society',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-CC101-1-1',
                'name'           => 'Introduction to Computing',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-CC102-1-1',
                'name'           => 'Computer Programming 1',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-MATH101-1-1',
                'name'           => 'Calculus 1',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-PHYS101-1-1',
                'name'           => 'Physics for Computer Science',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-RIZAL-1-1',
                'name'           => 'Life and Works of Rizal',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            // PATHFIT — non-tuition per CHED (isNstpSubject/isPathfitSubject will exclude from billing)
            [
                'code'           => 'BSCS-PATHFIT1-1-1',
                'name'           => 'PATHFIT 1 - Movement Competency Training',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            // NSTP — excluded from billing entirely
            [
                'code'           => 'BSCS-NSTP1-1-1',
                'name'           => 'NSTP 1 - National Service Training Program 1',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],

            // ================================================================
            // BS COMPUTER SCIENCE — 1st Year, 2nd Semester
            // ================================================================
            [
                'code'           => 'BSCS-GE4-1-2',
                'name'           => 'The Contemporary World',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-GE5-1-2',
                'name'           => 'Ethics',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-CC103-1-2',
                'name'           => 'Computer Programming 2',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-CC104-1-2',
                'name'           => 'Discrete Mathematics',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-MATH102-1-2',
                'name'           => 'Calculus 2',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-STAT101-1-2',
                'name'           => 'Statistics and Probability',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-PATHFIT2-1-2',
                'name'           => 'PATHFIT 2 - Exercise-based Fitness Activities',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSCS-NSTP2-1-2',
                'name'           => 'NSTP 2 - National Service Training Program 2',
                'course'         => 'BS Computer Science',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],

            // ================================================================
            // BSEET — 1st Year, 1st Semester
            // Billable: 19 lec units, 2 lab subjects
            // ================================================================
            [
                'code'           => 'BSEET-GE1-1-1',
                'name'           => 'Purposive Communication',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-GEELEC1-1-1',
                'name'           => 'Living in the IT Era',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-GE2-1-1',
                'name'           => 'Mathematics in the Modern World',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-GE3-1-1',
                'name'           => 'Science, Technology and Society',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-MATH101-1-1',
                'name'           => 'Calculus 1 - Differential Calculus',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-PHYS101-1-1',
                'name'           => 'Physics for Engineering Technologists',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-COMP101-1-1',
                'name'           => 'Integrated Software Applications 1',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-PATHFIT1-1-1',
                'name'           => 'PATHFIT 1 - Movement Competency Training',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-NSTP1-1-1',
                'name'           => 'NSTP 1 - National Service Training Program 1',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 0,
                'lab_units'      => 0,
                'units'          => 0,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],

            // ================================================================
            // BSEET — 1st Year, 2nd Semester
            // Billable: 19 lec units, 3 lab subjects
            // ================================================================
            [
                'code'           => 'BSEET-GEELEC2-1-2',
                'name'           => 'Peace Studies and Education',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-GE4-1-2',
                'name'           => 'The Contemporary World',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-MATH102-1-2',
                'name'           => 'Calculus 2 - Integral Calculus',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-CHEM101-1-2',
                'name'           => 'Chemistry for Engineering Technologists',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-FDB-1-2',
                'name'           => 'Fundamentals of Deformable Bodies',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-CAD1-1-2',
                'name'           => 'Computer-Aided Drafting',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-COMP102-1-2',
                'name'           => 'Integrated Software Applications 2',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-PATHFIT2-1-2',
                'name'           => 'PATHFIT 2 - Exercise-based Fitness Activities',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEET-NSTP2-1-2',
                'name'           => 'NSTP 2 - National Service Training Program 2',
                'course'         => 'BS Electrical Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 0,
                'lab_units'      => 0,
                'units'          => 0,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],

            // ================================================================
            // BSEECT — 1st Year, 1st Semester
            // Billable: 21 lec units, 3 lab subjects
            // ================================================================
            [
                'code'           => 'BSEECT-GE1-1-1',
                'name'           => 'Purposive Communication',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-GEELEC1-1-1',
                'name'           => 'Living in the IT Era',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-GE2-1-1',
                'name'           => 'Mathematics in the Modern World',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-GE3-1-1',
                'name'           => 'Science, Technology and Society',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-ELXT110-1-1',
                'name'           => 'Basic Electricity and Electronics',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-MATH101-1-1',
                'name'           => 'Calculus 1 - Differential Calculus',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-PHYS101-1-1',
                'name'           => 'Physics for Engineering Technologists',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 1,
                'units'          => 3,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-COMP101-1-1',
                'name'           => 'Integrated Software Applications',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-PATHFIT1-1-1',
                'name'           => 'PATHFIT 1 - Movement Competency Training',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-NSTP1-1-1',
                'name'           => 'NSTP 1 - National Service Training Program 1',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '1st Sem',
                'lec_units'      => 0,
                'lab_units'      => 0,
                'units'          => 0,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],

            // ================================================================
            // BSEECT — 1st Year, 2nd Semester
            // Billable: 20 lec units, 4 lab subjects
            // ================================================================
            [
                'code'           => 'BSEECT-GEELEC2-1-2',
                'name'           => 'Peace Studies and Education',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-ECE111-1-2',
                'name'           => 'Electronics 1: Electronics Devices and Circuits',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-EE110-1-2',
                'name'           => 'DC and AC Circuits',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-CHEM101-1-2',
                'name'           => 'Chemistry for Engineering Technologist',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-MATH102-1-2',
                'name'           => 'Calculus 2 - Integral Calculus',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 1,
                'units'          => 4,
                'has_lab'        => true,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => self::LAB_FEE_PER_SUBJ,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-CAD1-1-2',
                'name'           => 'Computer-Aided Drafting',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => self::TUITION_PER_UNIT,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-COMP102-1-2',
                'name'           => 'Computer Software Applications 2',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 2,
                'lab_units'      => 0,
                'units'          => 2,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-PATHFIT2-1-2',
                'name'           => 'PATHFIT 2 - Exercise-based Fitness Activities',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 3,
                'lab_units'      => 0,
                'units'          => 3,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
            [
                'code'           => 'BSEECT-NSTP2-1-2',
                'name'           => 'NSTP 2 - National Service Training Program 2',
                'course'         => 'BS Electronics Engineering Technology',
                'year_level'     => '1st Year',
                'semester'       => '2nd Sem',
                'lec_units'      => 0,
                'lab_units'      => 0,
                'units'          => 0,
                'has_lab'        => false,
                'price_per_unit' => 0,
                'lab_fee'        => 0,
                'is_active'      => true,
            ],
        ];

        $now = now()->toDateTimeString();

        foreach ($subjects as $subject) {
            DB::table('subjects')->updateOrInsert(
                ['code' => $subject['code']],
                array_merge($subject, ['updated_at' => $now])
            );

            // Set created_at only if this is a new row
            DB::table('subjects')
                ->where('code', $subject['code'])
                ->whereNull('created_at')
                ->update(['created_at' => $now]);
        }

        $this->command->info('✓ Seeded ' . count($subjects) . ' subjects (BSCS, BSEET, BSEECT — 1st Year only).');
        $this->command->warn('  → Add 2nd/3rd/4th year subjects when you have the official curriculum sheets.');
    }
}